const SUPABASE_URL = "https://xruivxqjdblnorhromyv.supabase.co";
const SUPABASE_KEY = "PASTE_YOUR_PUBLISHABLE_KEY_HERE";

const supabaseClient = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_KEY
);
const defaultData={
 settings:{heroTitle:"Premium Properties & Land, Curated.",heroText:"Discover thoughtfully selected homes, residential plots and commercial properties across Hyderabad — with direct, transparent guidance from VRV Estates.",agent:"Rahul Gabbeta",phone:"+91 9989698152",address:"Ramanthapur, Hyderabad, Telangana 500013"},
 properties:[
  {id:1,title:"A Well-Connected Home in Premnagar",type:"Independent House",location:"Premnagar, Amberpet",price:"₹1.50 Cr",area:"145 sq. yd.",bedrooms:"1",bathrooms:"7",parking:"Available",featured:true,description:"A well-connected family home near the main road, suitable for buyers looking for a central Hyderabad location.",amenities:"Parking, Main-road access, Multiple rooms",images:["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=900&q=80"]},
  {id:2,title:"A Spacious Family Home with Timeless Interiors",type:"Family Home",location:"Premnagar, Amberpet",price:"₹2.10 Cr",area:"180 sq. yd.",bedrooms:"3",bathrooms:"4",parking:"Available",featured:true,description:"A multi-level family residence with generous spaces and an established neighbourhood setting.",amenities:"Multiple levels, Parking, Family home",images:["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=900&q=80"]},
  {id:3,title:"Premium Residential Plot",type:"Residential Plot",location:"Uppal, Hyderabad",price:"₹78 L",area:"200 sq. yd.",bedrooms:"—",bathrooms:"—",parking:"Road access",featured:true,description:"A residential plot positioned for convenient access to established neighbourhoods and city connectivity.",amenities:"Road access, Residential zone, Clear approach",images:["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85"]},
  {id:4,title:"Strategic Commercial Space",type:"Commercial",location:"Habsiguda, Hyderabad",price:"₹1.85 Cr",area:"165 sq. yd.",bedrooms:"—",bathrooms:"2",parking:"Available",featured:false,description:"Commercial property suited for office, retail or professional use in a well-connected Hyderabad corridor.",amenities:"Road frontage, Parking, Commercial use",images:["https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=85"]},
  {id:5,title:"Modern Luxury Residence",type:"Luxury Home",location:"Banjara Hills, Hyderabad",price:"₹4.25 Cr",area:"310 sq. yd.",bedrooms:"4",bathrooms:"5",parking:"2 Cars",featured:false,description:"A refined residence for buyers seeking premium space, privacy and a prestigious Hyderabad address.",amenities:"Luxury interiors, Parking, Large living areas",images:["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85"]}
 ],
 enquiries:[]
};
let data=JSON.parse(localStorage.getItem("vrvEstatesData")||"null")||defaultData;
function save(){localStorage.setItem("vrvEstatesData",JSON.stringify(data))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2500)}
function propertyCard(p){
 return `<article class="card"><div class="card-img"><img src="${esc(p.images[0])}" alt="${esc(p.title)}"><span class="tag">${esc(p.type)}</span></div><div class="card-body"><div class="price">${esc(p.price)}</div><h3>${esc(p.title)}</h3><p class="muted">⌖ ${esc(p.location)}</p><div class="specs"><span>${esc(p.area)}</span><span>•</span><span>${esc(p.bedrooms)} Bed</span><span>•</span><span>${esc(p.bathrooms)} Bath</span></div><div class="card-footer"><span class="muted">${esc(p.parking)}</span><button class="link" onclick="viewProperty(${p.id})">View Property →</button></div></div></article>`
}
function renderSite(){
 document.getElementById("featuredGrid").innerHTML=data.properties.filter(p=>p.featured).slice(0,3).map(propertyCard).join("");
 document.getElementById("allGrid").innerHTML=data.properties.map(propertyCard).join("");
 document.getElementById("year").textContent=new Date().getFullYear();
}
function viewProperty(id){
 let p=data.properties.find(x=>x.id==id);if(!p)return;
 let pics=p.images||[];
 document.getElementById("propertyModalBody").innerHTML=`<div class="modal-head"><div><div class="eyebrow">${esc(p.type)}</div><h2 style="font-size:42px">${esc(p.title)}</h2><p class="muted">⌖ ${esc(p.location)}</p></div><button class="close" onclick="closeProperty()">×</button></div>
 <div class="gallery">${pics.slice(0,3).map((x,i)=>`<img src="${esc(x)}" alt="">`).join("")}</div>
 <div style="display:flex;justify-content:space-between;align-items:center;margin:24px 0"><div class="price">${esc(p.price)}</div><div class="actions"><a class="btn green" target="_blank" href="https://wa.me/919989698152?text=${encodeURIComponent("I'm interested in "+p.title+" - "+p.location)}">WhatsApp</a><a class="btn" href="tel:+919989698152">Call</a></div></div>
 <div class="detail-grid"><div class="detail-item"><small>Area</small><strong>${esc(p.area)}</strong></div><div class="detail-item"><small>Bedrooms</small><strong>${esc(p.bedrooms)}</strong></div><div class="detail-item"><small>Bathrooms</small><strong>${esc(p.bathrooms)}</strong></div><div class="detail-item"><small>Parking</small><strong>${esc(p.parking)}</strong></div></div>
 <h3 class="serif" style="font-size:28px;margin-bottom:8px">About this property</h3><p class="muted">${esc(p.description)}</p><h3 class="serif" style="font-size:28px;margin:25px 0 8px">Amenities</h3><p>${esc(p.amenities)}</p>
 <div style="margin-top:28px"><button class="btn gold full" onclick="bookVisit(${p.id})">Book Site Visit →</button></div>`;
 document.getElementById("propertyModal").classList.add("show")
}
function closeProperty(){document.getElementById("propertyModal").classList.remove("show")}
function bookVisit(id){let p=data.properties.find(x=>x.id==id);document.getElementById("propertyModalBody").innerHTML=`<div class="modal-head"><h2 style="font-size:35px">Book a <span>Site Visit</span></h2><button class="close" onclick="closeProperty()">×</button></div><p class="muted" style="margin-bottom:20px">${esc(p.title)}</p><form class="form" onsubmit="submitVisit(event,${id})"><div class="form-grid"><div class="field"><label>Name</label><input id="visitName" required></div><div class="field"><label>Phone</label><input id="visitPhone" required></div></div><div class="form-grid"><div class="field"><label>Date</label><input id="visitDate" required type="date"></div><div class="field"><label>Preferred time</label><input id="visitTime" required type="time"></div></div><button class="btn gold full">Request Site Visit</button></form>`}
function submitVisit(e,id){e.preventDefault();data.enquiries.push({id:Date.now(),name:document.getElementById("visitName").value,phone:document.getElementById("visitPhone").value,message:"Site visit: "+data.properties.find(p=>p.id==id).title+" | "+document.getElementById("visitDate").value+" "+document.getElementById("visitTime").value,date:new Date().toLocaleString(),status:"New"});save();closeProperty();toast("Site visit request received.")}
function submitEnquiry(e){e.preventDefault();data.enquiries.push({id:Date.now(),name:document.getElementById("enqName").value,phone:document.getElementById("enqPhone").value,message:document.getElementById("enqMsg").value,date:new Date().toLocaleString(),status:"New"});save();e.target.reset();toast("Thank you — enquiry submitted.")}
function openAdmin(){if(sessionStorage.getItem("vrvAdmin")==="1"){document.getElementById("adminOverlay").classList.add("show");adminTab("dashboard",document.querySelector('.sidebar button[data-tab="dashboard"]'))}else document.getElementById("loginOverlay").classList.add("show")}
function closeAdmin(){document.getElementById("adminOverlay").classList.remove("show")}
function login(e){e.preventDefault();if(document.getElementById("adminUser").value==="admin"&&document.getElementById("adminPass").value==="rahul@11"){sessionStorage.setItem("vrvAdmin","1");document.getElementById("loginOverlay").classList.remove("show");openAdmin();toast("Welcome to VRV Admin")}else toast("Invalid login")}
function logoutAdmin(){sessionStorage.removeItem("vrvAdmin");closeAdmin();toast("Logged out")}
function adminTab(tab,el){
 document.querySelectorAll(".sidebar button").forEach(b=>b.classList.remove("active"));if(el)el.classList.add("active");
 let c=document.getElementById("adminContent");
 if(tab==="dashboard"){c.innerHTML=`<div class="eyebrow">Overview</div><h2 style="font-size:40px;margin:8px 0 25px">Good day, <span>VRV.</span></h2><div class="stats"><div class="stat">Properties<b>${data.properties.length}</b></div><div class="stat">Featured<b>${data.properties.filter(p=>p.featured).length}</b></div><div class="stat">Enquiries<b>${data.enquiries.length}</b></div><div class="stat">New<b>${data.enquiries.filter(e=>e.status==="New").length}</b></div></div><div class="card" style="padding:20px"><h3 class="serif" style="font-size:25px">Recent enquiries</h3><div style="overflow:auto;margin-top:12px">${enquiryTable(5)}</div></div>`}
 if(tab==="properties"){c.innerHTML=`<div class="section-head" style="margin-bottom:20px"><div><div class="eyebrow">Content management</div><h2 style="font-size:40px">Properties</h2></div><button class="btn gold" onclick="editProperty()">+ Add Property</button></div><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Property</th><th>Location</th><th>Price</th><th>Featured</th><th>Actions</th></tr></thead><tbody>${data.properties.map(p=>`<tr><td><b>${esc(p.title)}</b><br><small class="muted">${esc(p.type)}</small></td><td>${esc(p.location)}</td><td>${esc(p.price)}</td><td>${p.featured?"Yes":"No"}</td><td><div class="admin-actions"><button class="smallbtn" onclick="editProperty(${p.id})">Edit</button><button class="smallbtn danger" onclick="deleteProperty(${p.id})">Delete</button></div></td></tr>`).join("")}</tbody></table></div>`}
 if(tab==="enquiries"){c.innerHTML=`<div class="eyebrow">Lead management</div><h2 style="font-size:40px;margin:8px 0 25px">Enquiries</h2><div style="overflow:auto"><table class="admin-table"><thead><tr><th>Name</th><th>Phone</th><th>Requirement</th><th>Date</th><th>Status</th><th></th></tr></thead><tbody>${data.enquiries.map(x=>`<tr><td>${esc(x.name)}</td><td><a href="tel:${esc(x.phone)}">${esc(x.phone)}</a></td><td>${esc(x.message)}</td><td>${esc(x.date)}</td><td>${esc(x.status)}</td><td><button class="smallbtn danger" onclick="deleteEnquiry(${x.id})">Delete</button></td></tr>`).join("")||'<tr><td colspan="6">No enquiries yet.</td></tr>'}</tbody></table></div>`}
 if(tab==="content"){c.innerHTML=`<div class="eyebrow">Edit website</div><h2 style="font-size:40px;margin:8px 0 25px">Website Content</h2><form class="form" onsubmit="saveContent(event)"><div class="field"><label>Hero title</label><input id="setTitle" value="${esc(data.settings.heroTitle)}"></div><div class="field"><label>Hero description</label><textarea id="setText">${esc(data.settings.heroText)}</textarea></div><div class="form-grid"><div class="field"><label>Agent name</label><input id="setAgent" value="${esc(data.settings.agent)}"></div><div class="field"><label>Phone</label><input id="setPhone" value="${esc(data.settings.phone)}"></div></div><div class="field"><label>Office address</label><input id="setAddress" value="${esc(data.settings.address)}"></div><button class="btn gold">Save Website Content</button></form><p class="muted" style="margin-top:25px;font-size:12px">For a production site, store these values in a server/database rather than browser localStorage.</p>`}
}
function enquiryTable(n=99){return data.enquiries.slice(-n).reverse().map(x=>`<div style="padding:13px 0;border-bottom:1px solid #333"><b>${esc(x.name)}</b> · ${esc(x.phone)}<div class="muted">${esc(x.message)} · ${esc(x.date)}</div></div>`).join("")||'<p class="muted">No enquiries yet.</p>'}
function editProperty(id=null){
 let p=id?data.properties.find(x=>x.id==id):{title:"",type:"Independent House",location:"",price:"",area:"",bedrooms:"",bathrooms:"",parking:"Available",featured:false,description:"",amenities:"",images:[""]};
 document.getElementById("propertyModalBody").innerHTML=`<div class="modal-head"><h2 style="font-size:35px">${id?"Edit":"Add"} <span>Property</span></h2><button class="close" onclick="closeProperty()">×</button></div><form class="form" onsubmit="saveProperty(event,${id||0})">
 <div class="form-grid"><div class="field"><label>Title</label><input id="pTitle" required value="${esc(p.title)}"></div><div class="field"><label>Type</label><select id="pType">${["Independent House","Family Home","Residential Plot","Commercial","Luxury Home"].map(x=>`<option ${x===p.type?"selected":""}>${x}</option>`).join("")}</select></div></div>
 <div class="form-grid"><div class="field"><label>Location</label><input id="pLocation" required value="${esc(p.location)}"></div><div class="field"><label>Price</label><input id="pPrice" required value="${esc(p.price)}"></div></div>
 <div class="form-grid"><div class="field"><label>Area</label><input id="pArea" value="${esc(p.area)}"></div><div class="field"><label>Parking</label><input id="pParking" value="${esc(p.parking)}"></div></div>
 <div class="form-grid"><div class="field"><label>Bedrooms</label><input id="pBeds" value="${esc(p.bedrooms)}"></div><div class="field"><label>Bathrooms</label><input id="pBaths" value="${esc(p.bathrooms)}"></div></div>
 <div class="field"><label>Description</label><textarea id="pDesc">${esc(p.description)}</textarea></div><div class="field"><label>Amenities</label><input id="pAmenities" value="${esc(p.amenities)}"></div>
 <div class="field"><label>Image URLs (one per line)</label><textarea id="pImages">${esc((p.images||[]).join("\\n"))}</textarea></div>
 <label style="display:flex;gap:10px;align-items:center"><input id="pFeatured" type="checkbox" ${p.featured?"checked":""} style="width:auto"> Featured property</label>
 <button class="btn gold full">Save Property</button></form>`;
 document.getElementById("propertyModal").classList.add("show");
}
function saveProperty(e,id){e.preventDefault();let obj={id:id||Date.now(),title:document.getElementById("pTitle").value,type:document.getElementById("pType").value,location:document.getElementById("pLocation").value,price:document.getElementById("pPrice").value,area:document.getElementById("pArea").value,bedrooms:document.getElementById("pBeds").value,bathrooms:document.getElementById("pBaths").value,parking:document.getElementById("pParking").value,description:document.getElementById("pDesc").value,amenities:document.getElementById("pAmenities").value,images:document.getElementById("pImages").value.split("\n").map(x=>x.trim()).filter(Boolean),featured:document.getElementById("pFeatured").checked};if(!obj.images.length)obj.images=["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80"];let i=data.properties.findIndex(x=>x.id==id);if(i>=0)data.properties[i]=obj;else data.properties.push(obj);save();renderSite();closeProperty();adminTab("properties",document.querySelector('.sidebar button[data-tab="properties"]'));toast(id?"Property updated":"Property added")}
function deleteProperty(id){if(confirm("Delete this property?")){data.properties=data.properties.filter(p=>p.id!=id);save();renderSite();adminTab("properties",document.querySelector('.sidebar button[data-tab="properties"]'));toast("Property deleted")}}
function deleteEnquiry(id){if(confirm("Delete this enquiry?")){data.enquiries=data.enquiries.filter(x=>x.id!=id);save();adminTab("enquiries",document.querySelector('.sidebar button[data-tab="enquiries"]'));toast("Enquiry deleted")}}
function saveContent(e){e.preventDefault();data.settings.heroTitle=document.getElementById("setTitle").value;data.settings.heroText=document.getElementById("setText").value;data.settings.agent=document.getElementById("setAgent").value;data.settings.phone=document.getElementById("setPhone").value;data.settings.address=document.getElementById("setAddress").value;save();document.querySelector("h1").innerHTML=esc(data.settings.heroTitle).replace(/, /g,",<br>");document.querySelector(".hero p").textContent=data.settings.heroText;toast("Website content saved")}
function goHome(){closeAdmin();window.scrollTo({top:0,behavior:"smooth"})}
document.getElementById("propertyModal").addEventListener("click",e=>{if(e.target.id==="propertyModal")closeProperty()});
renderSite();
